name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-static-analysis-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Run format check
        run: npm run check
      - name: Run lint
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-unit-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Run unit tests
        run: npm run test:unit

  integration-test:
    needs: [unit-test]
    concurrency:
      group: ${{ github.workflow }}-integration-test-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/postgres-job.yml
    with:
      run_command: npm run test:integration

  e2e:
    needs: [static-analysis, unit-test]
    concurrency:
      group: ${{ github.workflow }}-e2e-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/postgres-job.yml
    with:
      run_command: NODE_OPTIONS='--max-old-space-size=4096' npm run test:e2e
      needs_playwright: true
