name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Cancel in-progress runs on new commits to same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Run format check
        run: npm run check
      - name: Run lint
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Run unit tests
        run: npm run test:unit

  integration-test:
    needs: [unit-test]
    uses: ./.github/workflows/postgres-job.yml
    with:
      run_command: npm run test:integration

  e2e:
    needs: [static-analysis, unit-test, integration-test]
    uses: ./.github/workflows/postgres-job.yml
    with:
      run_command: npm run test:e2e
      needs_playwright: true
