name: Reusable PostgreSQL Job
on:
  workflow_call:
    inputs:
      run_command:
        required: true
        type: string
      needs_playwright:
        required: false
        type: boolean
        default: false

jobs:
  postgres-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Prevent hanging jobs
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/postgres-service
      - uses: ./.github/actions/setup-postgres

      # Conditional Playwright setup
      - if: inputs.needs_playwright
        name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
            **/node_modules/playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/playwright.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - if: inputs.needs_playwright && steps.playwright-cache.outputs.cache-hit != 'true'
        name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run tests
        env:
          NODE_ENV: test
          CI: true
        run: ${{ inputs.run_command }}
