name: Reusable PostgreSQL Job
on:
  workflow_call:
    inputs:
      run_command:
        required: true
        type: string
      needs_playwright:
        required: false
        type: boolean
        default: false

jobs:
  postgres-job:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Prevent hanging jobs
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/svelte_turbo_test_db
      PGUSER: postgres
      PGPASSWORD: postgres
      NODE_ENV: test
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: svelte_turbo_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL and setup database
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/svelte_turbo_test_db
          PGUSER: postgres
          PGPASSWORD: postgres
        run: |
          echo "Environment variables before database setup:"
          env | sort

          # Wait for PostgreSQL to be ready with increased timeout
          timeout 15s bash -c 'until pg_isready -h localhost -p 5432 -U postgres; do sleep 0.5; done'

          # Drop and recreate database to ensure clean state
          psql -h localhost -U postgres -c "DROP DATABASE IF EXISTS svelte_turbo_test_db;"
          psql -h localhost -U postgres -c "CREATE DATABASE svelte_turbo_test_db;"

          # Clean up schema and apply migrations
          cd packages/db
          NODE_ENV=test psql -h localhost -U postgres -d svelte_turbo_test_db -c "DROP TABLE IF EXISTS __drizzle_migrations CASCADE; DROP TYPE IF EXISTS user_status CASCADE;"
          NODE_ENV=test npx drizzle-kit generate
          NODE_ENV=test npx drizzle-kit push
          cd ../..

      # Conditional Playwright setup
      - if: inputs.needs_playwright
        name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
            **/node_modules/playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/playwright.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - if: inputs.needs_playwright && steps.playwright-cache.outputs.cache-hit != 'true'
        name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run tests
        env:
          NODE_ENV: test
          CI: true
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/svelte_turbo_test_db
          PGUSER: postgres
          PGPASSWORD: postgres
        run: |
          echo "Environment variables before tests:"
          env | sort

          ${{ inputs.run_command }}
